spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankdb
    username: bankdb
    password: bankdb
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
